Repository Kusitms-29th-Meetup-TeamE/Backend, pull requests merged in 2024-05, with the labels that each got.

#13 Feat: 온보딩 API 구현
  build.gradle
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ReadMainActivityRes.java
  src/main/java/com/meetup/teame/backend/domain/activity/entity/Activity.java
  src/main/java/com/meetup/teame/backend/domain/activity/entity/Personality.java
  src/main/java/com/meetup/teame/backend/domain/activity/repository/ActivityRepository.java
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/auth/config/SecurityConfig.java
  src/main/java/com/meetup/teame/backend/domain/personality/Personality.java
  src/main/java/com/meetup/teame/backend/domain/user/controller/UserController.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/request/OnboardingReq.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/User.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
  src/main/java/com/meetup/teame/backend/global/config/QueryDslConfig.java
  src/main/java/com/meetup/teame/backend/global/exception/ExceptionContent.java
  src/test/java/com/meetup/teame/backend/domain/user/controller/UserControllerTest.java
Labels: feature

#17 Feat: 채팅방 목록 api 구현
  src/main/java/com/meetup/teame/backend/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/dto/response/DirectChatRoomRes.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/dto/response/GroupChatRoomRes.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/dto/response/ReadDirectChatRoomsRes.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/dto/response/ReadGroupChatRoomsRes.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/entity/ChatType.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/entity/UserChatRoom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/custom/ChatRoomRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/custom/ChatRoomRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/meetup/teame/backend/domain/chatting/config/WebSocketConfig.java
  src/main/java/com/meetup/teame/backend/domain/chatting/document/ChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/User.java
Labels: feature

#19 Feat: 카카오 oauth 로그인 구현
  build.gradle
  src/main/java/com/meetup/teame/backend/domain/auth/config/SecurityConfig.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/JwtFilter.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/JwtProvider.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/UserAuthentication.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/dto/CustomUserDetails.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/dto/TokenInfo.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/service/CustomUserDetailsService.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/controller/KakaoController.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/dto/CreateOauthUserRequest.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/dto/CreateUserRequest.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/service/KakaoService.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/oauth/KakaoUserDto.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/oauth/UserTokenDto.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/Gender.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/User.java
  src/main/java/com/meetup/teame/backend/domain/user/repository/UserRepository.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: feature

#21 Fix: jwt 토큰 null 예외처리
  src/main/java/com/meetup/teame/backend/domain/auth/config/SecurityConfig.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/JwtFilter.java
Labels: fix

#23 Fix: 블루그린 배포 오류 수정
  .github/workflows/cicd.yml
Labels: fix

#28 Feat: 메일 서비스 및 서비스 자체 회원가입, 로그인 api
  build.gradle
  src/main/java/com/meetup/teame/backend/domain/auth/config/SecurityConfig.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/dto/TokenInfo.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/controller/KakaoController.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/dto/CreateOauthUserRequest.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/service/KakaoService.java
  src/main/java/com/meetup/teame/backend/domain/email/config/BCryptConfig.java
  src/main/java/com/meetup/teame/backend/domain/email/config/MailConfig.java
  src/main/java/com/meetup/teame/backend/domain/email/dto/EmailRequest.java
  src/main/java/com/meetup/teame/backend/domain/email/service/EmailService.java
  src/main/java/com/meetup/teame/backend/domain/login/controller/LoginController.java
  src/main/java/com/meetup/teame/backend/domain/login/dto/LoginRequest.java
  src/main/java/com/meetup/teame/backend/domain/login/service/LoginService.java
  src/main/java/com/meetup/teame/backend/domain/register/controller/RegisterController.java
  src/main/java/com/meetup/teame/backend/domain/register/dto/RegisterRequest.java
  src/main/java/com/meetup/teame/backend/domain/register/service/RegisterService.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/oauth/KakaoUserDto.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/oauth/UserTokenDto.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/User.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/templates/email.html
Labels: feature, fix

#30 웹소켓 채팅 api 구현
  Dockerfile
  build.gradle
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ReadMainActivityRes.java
  src/main/java/com/meetup/teame/backend/domain/auth/config/SecurityConfig.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/dto/response/ReadDirectChatRoomsRes.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/dto/response/ReadGroupChatRoomsRes.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/meetup/teame/backend/domain/chatting/config/WebSocketConfig.java
  src/main/java/com/meetup/teame/backend/domain/chatting/controller/ChattingController.java
  src/main/java/com/meetup/teame/backend/domain/chatting/document/ChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/chatting/dto/request/AppointmentChatMessageReq.java
  src/main/java/com/meetup/teame/backend/domain/chatting/dto/request/EmoticonChatMessageReq.java
  src/main/java/com/meetup/teame/backend/domain/chatting/dto/request/TextChatMessageReq.java
  src/main/java/com/meetup/teame/backend/domain/chatting/dto/response/ChatMessageLogRes.java
  src/main/java/com/meetup/teame/backend/domain/chatting/dto/response/ChatMessageRes.java
  src/main/java/com/meetup/teame/backend/domain/chatting/entity/ChatMessageType.java
  src/main/java/com/meetup/teame/backend/domain/chatting/entity/document/AppointmentChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/chatting/entity/document/ChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/chatting/entity/document/EmoticonChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/chatting/entity/document/TextChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/chatting/repository/ChattingRepository.java
  src/main/java/com/meetup/teame/backend/domain/chatting/service/ChattingService.java
  src/main/java/com/meetup/teame/backend/domain/experience/entity/ExperienceType.java
  src/main/java/com/meetup/teame/backend/domain/personality/Personality.java
  src/main/java/com/meetup/teame/backend/global/exception/ExceptionContent.java
  src/main/resources/application.yml
Labels: feature

#32 Feat: 경험나누기 api 구현
  src/main/java/com/meetup/teame/backend/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/meetup/teame/backend/domain/experience/controller/ExperienceController.java
  src/main/java/com/meetup/teame/backend/domain/experience/dto/request/ReadExperiencesReq.java
  src/main/java/com/meetup/teame/backend/domain/experience/dto/response/ExperienceRes.java
  src/main/java/com/meetup/teame/backend/domain/experience/dto/response/MyExperienceProfileRes.java
  src/main/java/com/meetup/teame/backend/domain/experience/dto/response/ReadExperiencesRes.java
  src/main/java/com/meetup/teame/backend/domain/experience/entity/Experience.java
  src/main/java/com/meetup/teame/backend/domain/experience/entity/ExperienceType.java
  src/main/java/com/meetup/teame/backend/domain/experience/repository/ExperienceRepository.java
  src/main/java/com/meetup/teame/backend/domain/experience/repository/custom/ExperienceRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/experience/repository/custom/ExperienceRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/experience/service/ExperienceService.java
  src/main/java/com/meetup/teame/backend/domain/personality/Personality.java
  src/main/java/com/meetup/teame/backend/global/exception/ExceptionContent.java
Labels: feature

#37 Feat: 채팅방 api 완성
  src/main/java/com/meetup/teame/backend/TestChatController.java
  src/main/java/com/meetup/teame/backend/TestChatReq.java
  src/main/java/com/meetup/teame/backend/TestChatRes.java
  src/main/java/com/meetup/teame/backend/domain/activity/entity/Activity.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/dto/response/DirectChatRoomRes.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/dto/response/GroupChatRoomRes.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/entity/Appointment.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/entity/ChatType.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/entity/DirectChatRoom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/entity/GroupChatRoom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/entity/UserChatRoom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/DirectChatRoomRepository.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/GroupChatRoomRepository.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/UserChatRoomRepository.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/custom/ChatRoomRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/custom/ChatRoomRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/custom/DirectChatRoomRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/custom/DirectChatRoomRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/custom/GroupChatRoomRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/repository/custom/GroupChatRoomRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/service/LastAppointmentScheduler.java
  src/main/java/com/meetup/teame/backend/domain/chatting/dto/request/AppointmentChatMessageReq.java
  src/main/java/com/meetup/teame/backend/domain/chatting/dto/response/ChatMessageRes.java
  src/main/java/com/meetup/teame/backend/domain/chatting/entity/document/AppointmentChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/chatting/entity/document/ChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/chatting/entity/document/EmoticonChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/chatting/entity/document/TextChatMessage.java
  src/main/java/com/meetup/teame/backend/domain/chatting/repository/ChattingRepository.java
  src/main/java/com/meetup/teame/backend/domain/chatting/service/ChattingService.java
  src/main/java/com/meetup/teame/backend/domain/experience/entity/Experience.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/User.java
  src/main/java/com/meetup/teame/backend/global/config/SchedulingConfig.java
  src/main/java/com/meetup/teame/backend/global/exception/ExceptionContent.java
  src/test/java/com/meetup/teame/backend/domain/user/controller/UserControllerTest.java
Labels: feature

#41 Feat: 후기 보내기, 후기 조회하기
  build.gradle
  src/main/java/com/meetup/teame/backend/domain/activity/controller/ActivityController.java
  src/main/java/com/meetup/teame/backend/domain/activity/dto/request/ReadActivitiesReq.java
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ActivityDetailsRes.java
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ActivityPageRes.java
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ActivitySummaryRes.java
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ReadActivitiesRes.java
  src/main/java/com/meetup/teame/backend/domain/activity/entity/Activity.java
  src/main/java/com/meetup/teame/backend/domain/activity/entity/AgencyType.java
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/activity/service/ActivityService.java
  src/main/java/com/meetup/teame/backend/domain/auth/config/SecurityConfig.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/SecurityContextProvider.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/dto/CustomUserDetails.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/service/CustomUserDetailsService.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/controller/KakaoController.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/service/KakaoService.java
  src/main/java/com/meetup/teame/backend/domain/like/repository/ActivityLikeRepository.java
  src/main/java/com/meetup/teame/backend/domain/personality/Personality.java
  src/main/java/com/meetup/teame/backend/domain/register/controller/RegisterController.java
  src/main/java/com/meetup/teame/backend/domain/review/controller/ReviewController.java
  src/main/java/com/meetup/teame/backend/domain/review/dto/request/CreateReviewReq.java
  src/main/java/com/meetup/teame/backend/domain/review/dto/response/ReviewRes.java
  src/main/java/com/meetup/teame/backend/domain/review/entity/Review.java
  src/main/java/com/meetup/teame/backend/domain/review/repository/ReviewRepository.java
  src/main/java/com/meetup/teame/backend/domain/review/repository/custom/ReviewRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/review/repository/custom/ReviewRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/review/service/ReviewService.java
  src/main/java/com/meetup/teame/backend/domain/user/controller/UserController.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/request/UpdateUserReq.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/response/UserInfoRes.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/Gender.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/User.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
  src/main/java/com/meetup/teame/backend/global/config/S3Config.java
  src/main/java/com/meetup/teame/backend/global/exception/ExceptionContent.java
  src/main/resources/application.yml
Labels: feature, fix

#45 Feat: 마이페이지 - 배움내역보기 api 구현
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ActivitySummaryRes.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/service/LastAppointmentScheduler.java
  src/main/java/com/meetup/teame/backend/domain/experience/entity/Experience.java
  src/main/java/com/meetup/teame/backend/domain/review/controller/ReviewController.java
  src/main/java/com/meetup/teame/backend/domain/review/dto/request/CreateReviewReq.java
  src/main/java/com/meetup/teame/backend/domain/review/dto/response/MyReviewRes.java
  src/main/java/com/meetup/teame/backend/domain/review/dto/response/ReadReviewsByMeRes.java
  src/main/java/com/meetup/teame/backend/domain/review/dto/response/ReviewByMeRes.java
  src/main/java/com/meetup/teame/backend/domain/review/dto/response/ReviewRes.java
  src/main/java/com/meetup/teame/backend/domain/review/entity/Review.java
  src/main/java/com/meetup/teame/backend/domain/review/repository/ReviewRepository.java
  src/main/java/com/meetup/teame/backend/domain/review/repository/custom/ReviewRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/review/repository/custom/ReviewRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/review/service/ReviewService.java
  src/main/java/com/meetup/teame/backend/domain/user/controller/UserController.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/User.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
  src/main/java/com/meetup/teame/backend/global/exception/ExceptionContent.java
Labels: feature

#48 Feat: 나의 후기 확인 api
  src/main/java/com/meetup/teame/backend/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/meetup/teame/backend/domain/experience/entity/Experience.java
  src/main/java/com/meetup/teame/backend/domain/experience/service/ExperienceService.java
  src/main/java/com/meetup/teame/backend/domain/like/controller/LikeController.java
  src/main/java/com/meetup/teame/backend/domain/like/entity/ActivityLike.java
  src/main/java/com/meetup/teame/backend/domain/like/repository/ActivityLikeRepository.java
  src/main/java/com/meetup/teame/backend/domain/like/service/LikeService.java
  src/main/java/com/meetup/teame/backend/domain/review/dto/response/MyReviewRes.java
  src/main/java/com/meetup/teame/backend/domain/review/entity/Review.java
  src/main/java/com/meetup/teame/backend/domain/review/repository/custom/ReviewRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/review/repository/custom/ReviewRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/review/service/ReviewService.java
  src/main/java/com/meetup/teame/backend/domain/user/controller/UserController.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
Labels: feature

#50 Fix: 메인페이지 api 이미지 정보 추가
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ReadMainActivityRes.java
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/auth/jwt/SecurityContextProvider.java
  src/main/java/com/meetup/teame/backend/domain/auth/oauth/controller/KakaoController.java
  src/main/java/com/meetup/teame/backend/domain/experience/repository/custom/ExperienceRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/experience/repository/custom/ExperienceRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/user/controller/UserController.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/response/ReadCalenderRes.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/response/ReadExperienceProfileRes.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
Labels: feature

#51 Feat: 나의 배움 프로필 api
  src/main/java/com/meetup/teame/backend/domain/experience/entity/Experience.java
  src/main/java/com/meetup/teame/backend/domain/experience/repository/ExperienceRepository.java
  src/main/java/com/meetup/teame/backend/domain/like/service/LikeService.java
  src/main/java/com/meetup/teame/backend/domain/user/controller/UserController.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/request/MyExperienceReq.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/response/MyExperienceRes.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/response/ReadExperienceProfileRes.java
  src/main/java/com/meetup/teame/backend/domain/user/entity/User.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
Labels: feature

#54 Fix: 배움나누기 목록 조회 api 수정
  src/main/java/com/meetup/teame/backend/domain/chatroom/service/LastAppointmentScheduler.java
  src/main/java/com/meetup/teame/backend/domain/experience/dto/response/ExperienceRes.java
  src/main/java/com/meetup/teame/backend/domain/experience/entity/Experience.java
Labels: fix

#56 Fix: 활동 목록 dto 수정
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ActivitySummaryRes.java
Labels: fix

#57 Fix: 활동 상세 dto 수정
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ActivityDetailsRes.java
Labels: fix

#59 Fix: 활동 엔티티
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ActivityDetailsRes.java
  src/main/java/com/meetup/teame/backend/domain/activity/entity/Activity.java
Labels: fix

#60 Fix: 채팅방 상태를 활동 참여자 수 데이터에 반영
  src/main/java/com/meetup/teame/backend/domain/activity/entity/Activity.java
  src/main/java/com/meetup/teame/backend/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/meetup/teame/backend/domain/experience/dto/response/ExperienceRes.java
Labels: fix

#64 Fix: 활동 칩 추가
  src/main/java/com/meetup/teame/backend/domain/activity/dto/response/ActivitySummaryRes.java
Labels: fix

#66 Fix: 리뷰 작성시 작성일 반영
  src/main/java/com/meetup/teame/backend/domain/review/entity/Review.java
Labels: fix

#67 Fix: 활동 다중 선택 가능
  src/main/java/com/meetup/teame/backend/domain/activity/dto/request/ReadActivitiesReq.java
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/activity/service/ActivityService.java
Labels: fix

#68 Docs: 아키텍처, ERD 리드미에 추가
  README.md
Labels: documentation

#70 Fix: 이메일 인증 이슈
  src/main/java/com/meetup/teame/backend/domain/register/controller/RegisterController.java
Labels: fix

#73 Fix: 활동 페이징 처리 수정
  src/main/java/com/meetup/teame/backend/domain/activity/service/ActivityService.java
  src/main/java/com/meetup/teame/backend/domain/register/service/RegisterService.java
  src/main/java/com/meetup/teame/backend/domain/review/controller/ReviewController.java
Labels: fix

#75 Fix: 메인페이지 추천활동 수정
  src/main/java/com/meetup/teame/backend/domain/activity/service/ActivityService.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
Labels: fix

#76 Fix: 활동 목록 온보딩 반영 및 익명 유저 사용 반영
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/activity/service/ActivityService.java
  src/main/java/com/meetup/teame/backend/domain/auth/config/SecurityConfig.java
Labels: fix

#78 Fix: 활동 온보딩 필터링
  src/main/java/com/meetup/teame/backend/domain/activity/repository/custom/ActivityRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/activity/service/ActivityService.java
  src/main/java/com/meetup/teame/backend/domain/experience/dto/response/ReadExperienceDetailRes.java
  src/main/java/com/meetup/teame/backend/domain/experience/repository/custom/ExperienceRepositoryCustom.java
  src/main/java/com/meetup/teame/backend/domain/experience/repository/custom/ExperienceRepositoryImpl.java
  src/main/java/com/meetup/teame/backend/domain/experience/service/ExperienceService.java
Labels: fix

#80 Feat: 유저 온보딩 정보 조히 api
  src/main/java/com/meetup/teame/backend/domain/user/controller/UserController.java
  src/main/java/com/meetup/teame/backend/domain/user/dto/response/UserOnboardingRes.java
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
Labels: feature

#82 Fix: 배움 나누기 페이지 수식 수정
  src/main/java/com/meetup/teame/backend/domain/experience/service/ExperienceService.java
Labels: fix

#88 Fix: 카카오 이미지 저장
  src/main/java/com/meetup/teame/backend/domain/user/service/UserService.java
Labels: fix

#92 Docs: Update README.md
  README.md
Labels: documentation
